@startuml Sequence
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
    AttributeIconSize 0
}
'skinparam style strictuml
skinparam stereotypeCBackgroundColor White
skinparam stereotypeIBackgroundColor White
skinparam stereotypeEBackgroundColor White
skinparam stereotypeABackgroundColor White
skinparam linetype ortho

actor user

box "Image Duplication Checker"
hide footbox

collections "API Gateway"
user -> "API Gateway" ++ : /upload

collections Lambda
"API Gateway" -> Lambda : /upload

Lambda -> Lambda : Hashing

database Redis
Lambda -> Redis ++ : GetCache
return 200 OK

database DynamoDB
Lambda -> DynamoDB ++ : Read
return 200 OK

storage S3


end box
@enduml